### ISSUE TITLE
Panic เพราะหา K8s version บน Windows ที่ match กันไม่เจอ

### ISSUE THREAD

**Issue by chanwit** [chanwit/ske#11]
**เวอร์ชั่นของ SKE:**
master 4fb5b185cd8fae176b5656945014b8b9508cfe09

**เวอร์ชั่นของ Docker: (จากคำสั่ง `docker version`,`docker info`)**
Docker 18.03.2-ke-1

**Operating system และ รุ่น kernel: (จากคำสั่ง `cat /etc/os-release`, `uname -r`)**
Ubuntu Xenial 16.04

**ชนิดและสภาพแวดล้อมของเครื่อง host: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**ไฟล์ cluster.yml:**
-

**วิธีการทำซ้ำให้เกิดบั๊ก:**
`./ske`

**ผลลัพธ์ชองบั๊ก:**
```
panic: K8s version  is not found in AllK8sWindowsVersions map

goroutine 1 [running]:
github.com/rancher/rke/vendor/github.com/rancher/types/apis/management.cattle.io/v3.initWindows()
        /go/src/github.com/rancher/rke/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go:198 +0x3c2
github.com/rancher/rke/vendor/github.com/rancher/types/apis/management.cattle.io/v3.init.1()
        /go/src/github.com/rancher/rke/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go:615 +0x35e
github.com/rancher/rke/vendor/github.com/rancher/types/apis/management.cattle.io/v3.init()
        /go/src/github.com/rancher/rke/vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_user_lifecycle_adapter.go:52 +0xeccb
github.com/rancher/rke/cmd.init()
        /go/src/github.com/rancher/rke/cmd/version.go:38 +0x5c
main.init()
        /go/src/github.com/rancher/rke/main.go:54 +0x55
```

**Comment by khajer** [comment]
/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go
`allK8sWindowsVersions = ...`
`"v1.10.6-ske1-1",`
`"v1.10.7-ske1-1",`
`"v1.10.7-ske1-2"`
ผมไม่ชัว version อะครับ 
allK8sWindowsVersions = ...
"v1.10.6-ske1-1": {
			NginxProxy:         m("rancher/nginx-proxy:v0.0.1-nanoserver-1803"),
			KubernetesBinaries: m("rancher/hyperkube:v1.11.2-nanoserver-1803"),
			FlannelCNIBinaries: m("rancher/flannel-cni:v0.0.1-nanoserver-1803"),
			CalicoCNIBinaries:  m("rancher/calico-cni:v0.0.1-nanoserver-1803"),
			CanalCNIBinaries:   m("rancher/canal-cni:v0.0.1-nanoserver-1803"),
			KubeletPause:       m("rancher/kubelet-pause:v0.0.1-nanoserver-1803"),
		},
		"v1.10.7-ske1-1": {
			NginxProxy:         m("rancher/nginx-proxy:v0.0.1-nanoserver-1803"),
			KubernetesBinaries: m("rancher/hyperkube:v1.11.2-nanoserver-1803"),
			FlannelCNIBinaries: m("rancher/flannel-cni:v0.0.1-nanoserver-1803"),
			CalicoCNIBinaries:  m("rancher/calico-cni:v0.0.1-nanoserver-1803"),
			CanalCNIBinaries:   m("rancher/canal-cni:v0.0.1-nanoserver-1803"),
			KubeletPause:       m("rancher/kubelet-pause:v0.0.1-nanoserver-1803"),
		},
		"v1.10.7-ske1-2": {
			NginxProxy:         m("rancher/nginx-proxy:v0.0.1-nanoserver-1803"),
			KubernetesBinaries: m("rancher/hyperkube:v1.11.2-nanoserver-1803"),
			FlannelCNIBinaries: m("rancher/flannel-cni:v0.0.1-nanoserver-1803"),
			CalicoCNIBinaries:  m("rancher/calico-cni:v0.0.1-nanoserver-1803"),
			CanalCNIBinaries:   m("rancher/canal-cni:v0.0.1-nanoserver-1803"),
			KubeletPause:       m("rancher/kubelet-pause:v0.0.1-nanoserver-1803"),
		},

**Comment by chanwit** [comment]
ไม่ชัวร์เหมือนกัน
ว่าจะแค่เอาตัว check ที่ทำให้ panic ออกไปก่อน

**Comment by chanwit** [comment]
@khajer ใช้แบบที่ข่าทำดีกว่า ปะไว้แค่ "v1.10.7-ske1-2": { } มันน่าจะได้ (มั้ย?)
